### ISSUE TITLE
Infrastructure: Pros/Cons of Heroku vs. AWS for hosting

### ISSUE THREAD

**Issue by abarganier** [abarganier/ColonyCounter#10]
Come up with a pros/cons list of AWS vs. Heroku. Things to consider are pricing, length of free trials, ease of use & deployment (this is a big one), limitations, etc.

**Comment by pfreiter09** [comment]
Researched as follows:

Cost: Both platforms have a free tier, AWS' free tier has 750 free hours per month, Heroku usage is unlimited.

Storage Space:
Heroku offers 512MB of RAM, with 100MB of additional storage space.

AWS offers slightly more RAM, but no extra storage space for you to develop. Also, the given amount of RAM was for the tier about one higher from the free tier.

Power:
The two have similar processing power, with AWS having a slight edge.

Deployment:

AWS does not offer any tools for deployment so it must be done manually through another service.

Heroku has some issues merging its file system with your own projects, but all the deployment is handled through the application itself.

https://smashingboxes.com/blog/heroku-vs-amazon-web-services/

For additional consideration.

**Comment by zceaton** [comment]
Settled on AWS, closing.
