### ISSUE TITLE
Front-End: Research Landing Page Tutorials

### ISSUE THREAD

**Issue by zceaton** [abarganier/ColonyCounter#12]
Find tutorials/examples on web app landing page tutorials in AngularJS.  Compile the information into some sort of .txt file or whatever you find best and commit it to the Front-End directory of the prototype branch of the repo.

**Comment by icemanf15** [comment]
https://github.com/revolunet/angular-carousel

https://github.com/mihnsen/ui-carousel

**Comment by abarganier** [comment]
Let's close this one out and move on to issue #28 for implementation
