### ISSUE TITLE
Front-End: Research AngularJS GUI examples/tutorials

### ISSUE THREAD

**Issue by zceaton** [abarganier/ColonyCounter#13]
Find tutorials/examples on GUIs in AngularJS.  Compile the information into some sort of .txt file or whatever you find best and commit it to the Front-End directory of the prototype branch of the repo.

**Comment by abarganier** [comment]
A couple we saw today:

https://github.com/flatlogic/angular-material-dashboard

https://github.com/creativetimofficial/material-dashboard-angular

https://github.com/start-angular/sb-admin-angular

**Comment by zceaton** [comment]
We've settled on a UI template and we're in the process of purging it of irrelevant content and repopulating for the prototype.  Closing issue,
