### ISSUE TITLE
Front-End: Create image upload form

### ISSUE THREAD

**Issue by abarganier** [abarganier/ColonyCounter#27]
In the main area, you can overwrite what's currently in `DashboardController.html` with the HTML for an image upload, and you can use `DashboardController.js` to add any behavior as needed.

Here's some inspiration for how that should look:

https://prnt.sc/

https://imgbb.com/

https://imgur.com/upload

You might also benefit from searches for tutorials, such as: https://www.google.com/search?safe=off&q=making+an+image+upload+view+tutorial&oq=making+an+image+upload+view+tutorial&gs_l=psy-ab.3...8206.10338.0.10393.13.11.0.0.0.0.248.1274.0j5j2.7.0....0...1.1.64.psy-ab..7.4.739...33i22i29i30k1.0.zSPVDup30Pk

**Comment by abarganier** [comment]
Note: since the tutorial carousel requires screenshots, this issue is somewhat of a blocker when it comes to finishing issue #28

**Comment by zceaton** [comment]
Merged to the prototype branch,

**Comment by abarganier** [comment]
Looks good
