### ISSUE TITLE
Front-End: Implement landing page tutorial

### ISSUE THREAD

**Issue by abarganier** [abarganier/ColonyCounter#28]
Now that we've thought about the landing page tutorial, it's time to implement the carousel. Note that issue #27 might block this task somewhat if screenshots are needed, but at the very least we can set up the carousel with some dummy images and then just easily replace them once the upload form is complete.

**Comment by abarganier** [comment]
Note, we need to review/merge the PR associated with #26 into the `prototype` branch before starting this task.

**Comment by zceaton** [comment]
Implemented.
