### ISSUE TITLE
Collab: Create (front-end only) login widget for navigation

### ISSUE THREAD

**Issue by abarganier** [abarganier/ColonyCounter#60]
Add a Front-End login widget to the navigation bar.

**Comment by pfreiter09** [comment]
This is a **front-end only** feature and does not require any back-end support or authentication; no back-end code manipulation should be necessary for implementation.

Ideally, a drop-down arrow, with fields for username, password, and submission would be preferred. Design should lend itself to being intuitive.

We are using the AngularJS shell for our front-end. Collaborations should be created on the "collab" branch of our repository.
