### ISSUE TITLE
Collab: Add ability to select/upload multiple files to the front end

### ISSUE THREAD

**Issue by abarganier** [abarganier/ColonyCounter#61]

**Comment by zceaton** [comment]
Add the ability to select multiple files with the existing submit button in DashboardController.  You'll then have to update the POST request in the imageFactory.js.

Here are some potentially helpful links to help you get started:
-https://stackoverflow.com/questions/31404502/upload-multiple-files-in-angular
-http://tutlane.com/tutorial/angularjs/angularjs-http-post-method-http-post-with-parameters-example
